name: SlotMachine
description: A Dart app that uses Angular
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular: "1.1.2+2"
  browser: ">=0.10.0+2 <0.11.0"
  dart_to_js_script_rewriter: "1.0.1"
  js: "^0.6.0"
transformers:
- dart_to_js_script_rewriter
- angular:
   $exclude: ['test/**']
   html_files:
     - lib/app_component.html



